apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-orchard
  annotations:
    meta.crossplane.io/maintainer: Ravan <ravan.naidoo@suse.com>
    meta.crossplane.io/source: github.com/ravan/provider-orchard
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider for Orchard - manages Tart VMs on macOS with cloud-init style startup scripts.
spec:
  capabilities:
    - safe-start
